version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend:ro
      - ./openapi.yml:/app/openapi.yml:ro
    ports:
      - "8000:8000"
    networks:
      - app-net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge 